// GENERATED by math/generate.py — do not edit.
// Mirror of the on-chain paytable. The contract stays authoritative; this file
// exists so the UI can price a pull before a transaction is signed.

export type Tier = {
  tier: number;
  prize: string;
  weight: number;        // ppm, row sums to PROB_SCALE
  multiplier: number;    // centi-units, 100 = 1.00x
  charm: string | null;
};

export type Cabinet = {
  id: number;
  key: string;
  name: string;
  blurb: string;
  volatility: 'low' | 'medium' | 'high';
  tiers: Tier[];
};

export const PROB_SCALE = 1_000_000;
export const MULT_SCALE = 100;
export const DECLARED_RTP_PPM = 960000;
export const TIER_TOP = 3;
export const CABINETS: Cabinet[] = [
  {
    "id": 0,
    "key": "penny",
    "name": "Penny Arcade",
    "blurb": "Fast cabinet. Small prizes, the claw slips half the time.",
    "volatility": "low",
    "tiers": [
      {
        "tier": 0,
        "prize": "slip",
        "weight": 500000,
        "multiplier": 0,
        "charm": null
      },
      {
        "tier": 1,
        "prize": "Tin Robot",
        "weight": 360000,
        "multiplier": 160,
        "charm": "tin-robot"
      },
      {
        "tier": 2,
        "prize": "Glass Cat",
        "weight": 110000,
        "multiplier": 240,
        "charm": "glass-cat"
      },
      {
        "tier": 3,
        "prize": "Porcelain Swan",
        "weight": 30000,
        "multiplier": 400,
        "charm": "porcelain-swan"
      }
    ]
  },
  {
    "id": 1,
    "key": "midway",
    "name": "Midway",
    "blurb": "Balanced cabinet. The grip holds often enough to keep you pulling.",
    "volatility": "medium",
    "tiers": [
      {
        "tier": 0,
        "prize": "slip",
        "weight": 780000,
        "multiplier": 0,
        "charm": null
      },
      {
        "tier": 1,
        "prize": "Neon Jelly",
        "weight": 150000,
        "multiplier": 200,
        "charm": "neon-jelly"
      },
      {
        "tier": 2,
        "prize": "Crystal Fox",
        "weight": 55000,
        "multiplier": 600,
        "charm": "crystal-fox"
      },
      {
        "tier": 3,
        "prize": "Golden Koi",
        "weight": 15000,
        "multiplier": 2200,
        "charm": "golden-koi"
      }
    ]
  },
  {
    "id": 2,
    "key": "vault",
    "name": "The Vault",
    "blurb": "One cabinet in the back. The claw almost never holds, and when it does...",
    "volatility": "high",
    "tiers": [
      {
        "tier": 0,
        "prize": "slip",
        "weight": 735000,
        "multiplier": 0,
        "charm": null
      },
      {
        "tier": 1,
        "prize": "Obsidian Beetle",
        "weight": 240000,
        "multiplier": 150,
        "charm": "obsidian-beetle"
      },
      {
        "tier": 2,
        "prize": "Ivory Idol",
        "weight": 20000,
        "multiplier": 600,
        "charm": "ivory-idol"
      },
      {
        "tier": 3,
        "prize": "Sunken Crown",
        "weight": 5000,
        "multiplier": 9600,
        "charm": "sunken-crown"
      }
    ]
  }
];

/** RTP of a cabinet recomputed from the emitted table, in ppm. */
export function rtpPpm(cabinet: Cabinet): number {
  const numerator = cabinet.tiers.reduce((acc, t) => acc + t.weight * t.multiplier, 0);
  return (numerator * 1_000_000) / (PROB_SCALE * MULT_SCALE);
}

/** Probability (0..1) of a tier in a cabinet. */
export function tierProbability(cabinet: Cabinet, tier: number): number {
  return cabinet.tiers[tier].weight / PROB_SCALE;
}

/** Payout in base units for a wager and tier — floor, exactly like `_payout`. */
export function payoutFor(wager: bigint, cabinet: Cabinet, tier: number): bigint {
  return (wager * BigInt(cabinet.tiers[tier].multiplier)) / BigInt(MULT_SCALE);
}

/** Worst-case payout, used to clamp the bet input against host risk limits. */
export function maxMultiplierX(cabinet: Cabinet): number {
  return cabinet.tiers[TIER_TOP].multiplier / MULT_SCALE;
}

/**
 * Client-side mirror of `_draw`: rejection sampling over [0, PROB_SCALE) from a
 * 32-byte randomness word, then cumulative weights. Used for the standalone
 * demo only — inside the host the outcome comes from the chain.
 */
export function drawFromRandomness(cabinet: Cabinet, randomness: bigint): { tier: number; draw: number } {
  const limit = Math.floor(2 ** 32 / PROB_SCALE) * PROB_SCALE;
  for (let i = 0; i < 8; i++) {
    const candidate = Number((randomness >> BigInt(i * 32)) & 0xffffffffn);
    if (candidate >= limit) continue;
    const r = candidate % PROB_SCALE;
    let acc = 0;
    for (let t = 0; t < cabinet.tiers.length; t++) {
      acc += cabinet.tiers[t].weight;
      if (r < acc) return { tier: t, draw: r };
    }
  }
  const fallback = Number((randomness ^ (randomness >> 64n)) % BigInt(PROB_SCALE));
  let acc = 0;
  for (let t = 0; t < cabinet.tiers.length; t++) {
    acc += cabinet.tiers[t].weight;
    if (fallback < acc) return { tier: t, draw: Math.abs(fallback) };
  }
  return { tier: TIER_TOP, draw: 0 };
}

// SessionPhase enum from ICasinoGameV2.sol
export const PHASE_SETTLED = 3;
export const PHASE_FORFEITED = 4;
export const PHASE_CANCELLED = 5;
export const PHASE_WAITING_RANDOMNESS = 1;

export function isTerminalPhase(phase: number | undefined): boolean {
  return phase === PHASE_SETTLED || phase === PHASE_FORFEITED || phase === PHASE_CANCELLED;
}
