// Enumerates every reel stop combination of example/game.ts into the base settlement table and
// the display mapping. Win weights are combination counts; the miss weight is set for the target
// RTP, so the reels only decide what a prize looks like, never how often it pays.
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { formatPrize, greatestCommonDivisor } from '../src/tier-list.ts';
import { encodeSeed, PRIZE_DENOMINATOR, prizeUnits, REELS, type Stops } from './game.ts';

const TARGET_RTP = { numerator: 24n, denominator: 25n };
const here = import.meta.dirname;

const seedsByUnits = new Map<number, string[]>();
for (let a = 0; a < REELS[0].length; a++) {
  for (let b = 0; b < REELS[1].length; b++) {
    for (let c = 0; c < REELS[2].length; c++) {
      const stops: Stops = [a, b, c];
      const units = prizeUnits(stops);
      seedsByUnits.set(units, [...(seedsByUnits.get(units) ?? []), encodeSeed(stops)]);
    }
  }
}

const winning = [...seedsByUnits.entries()]
  .filter(([units]) => units > 0)
  .sort(([a], [b]) => a - b)
  .map(([units, seeds]) => ({ units: BigInt(units), count: BigInt(seeds.length) }));
const winningWeight = winning.reduce((sum, tier) => sum + tier.count, 0n);
const prizeSum = winning.reduce((sum, tier) => sum + tier.units * tier.count, 0n);

// RTP = prizeSum / (denominator × totalWeight) = target, with every weight an integer.
const targetUnits = PRIZE_DENOMINATOR * TARGET_RTP.numerator;
const scale = targetUnits / greatestCommonDivisor(prizeSum * TARGET_RTP.denominator, targetUnits);
const totalWeight = (prizeSum * scale * TARGET_RTP.denominator) / targetUnits;
const missWeight = totalWeight - winningWeight * scale;
if (missWeight < 0n) {
  throw new Error('The reels pay more than the target RTP even without misses; lower the paytable');
}

const tierList = [
  '# Generated by example/generate.ts from the reel strips in example/game.ts. Do not edit by hand.',
  'prize,weight',
  `0,${missWeight}`,
  ...winning.map(tier => `${formatPrize(tier.units, PRIZE_DENOMINATOR)},${tier.count * scale}`),
].join('\n');
writeFileSync(resolve(here, 'base.csv'), `${tierList}\n`);

const seeds = Object.fromEntries(
  [...seedsByUnits.entries()].sort(([a], [b]) => a - b).map(([units, list]) => [units, list]),
);
writeFileSync(
  resolve(here, 'display-mapping.json'),
  `${JSON.stringify({ prizeDenominator: Number(PRIZE_DENOMINATOR), seeds })}\n`,
);

const naturalRtp = Number(prizeSum) / Number(PRIZE_DENOMINATOR * winningWeight);
const combinations = REELS.reduce((product, strip) => product * strip.length, 1);
console.log(
  `${winning.length} prizes, ${combinations} reel combinations, ${seedsByUnits.get(0)?.length ?? 0} of them misses\n` +
    `hit rate ${((Number(winningWeight * scale) / Number(totalWeight)) * 100).toFixed(2)}% ` +
    `(natural ${((Number(winningWeight) / combinations) * 100).toFixed(2)}%)\n` +
    `top prize ${formatPrize(winning[winning.length - 1].units, PRIZE_DENOMINATOR)}x, ` +
    `winning mass RTP ${(naturalRtp * 100).toFixed(2)}% before misses, table RTP ${Number(TARGET_RTP.numerator * 100n) / Number(TARGET_RTP.denominator)}%`,
);
